### ISSUE TITLE
Add more methods to `AbiJson` and items

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/core#101]
Like iterators from `ethabi::*`

**Comment by andyrobert3** [comment]
@DaniPopes could you elaborate more on this?

I want to work on this issue!

**Comment by DaniPopes** [comment]
Sure, you can check them out here:
- [`ethabi::Contract`](https://docs.rs/ethabi/latest/ethabi/struct.Contract.html#impl-Contract)
- other structs like Function, etc have since been implemented

Some extra notes:
- functions which return `Result` should instead return `Option`, since it's a better API:
  `fn function(&self, name: &str) -> Option<&Function>` 
- iterator functions should not return new-type iterators, but should just be `Flatten<Values<..>>`: `fn functions(&self) -> Flatten<Values<'_, String, Function>>`

**Comment by prestwich** [comment]
i kinda dislike the ethabi decision to return the first function when there are multiple with the same name. it means that serde deser and json ordering leak into program behavior. Should we instead have something like `fn function(&self, name: &str) -> Option<&[Function]> `

**Comment by andyrobert3** [comment]
for this week, will be starting this

was tackling another issue last week in foundry https://github.com/foundry-rs/foundry/pull/5266

**Comment by prestwich** [comment]
cool, also check out @DaniPopes work in #164

**Comment by andyrobert3** [comment]
made draft PR for the implementation logic

will be following #164 -> `crates/json-abi/tests/test.rs` to write the tests for each of the methods introduced
