### ISSUE TITLE
Add `ParamKind` to json-abi `{,Event}Param`

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/core#102]
currently the `type` field is unparsed, while `ethabi` users expect a parsed `ParamKind` enum. This would also remove the intermediate enum between the `{Simple,Complex}` structs

**Comment by cjeva10** [comment]
Hi, I'm interested in working on this - do we mostly want to lift from the `ethabi` enum `ParamType`? 

If so I can start working on a module to modify it to fit our existing code.

**Comment by prestwich** [comment]
This got somewhat re-imagined from when we wrote the issue. Right now, the json-abi is dependency-free, and used in `sol!` so it cannot depend on `dyn-abi` as that would cause a dep cycle

@DaniPopes can you update the issue with the current thinking?

**Comment by DaniPopes** [comment]
This is no longer planned, see #210
