### ISSUE TITLE
[Feature] Serde Serialization for U256 etc.

### ISSUE THREAD

**Issue by miracle2k** [alloy-rs/core#193]
### Component

primitives

### Describe the feature you would like

This works:

```
#[derive(Debug, Serialize, Deserialize)]
pub(crate) struct TokenMint {
    pub token: Uint<256, 4>,
}
```

But this doesn't:

```
#[derive(Debug, Serialize, Deserialize)]
pub(crate) struct TokenMint {
    pub token: U256
}
```

It gives: `the trait `Deserialize<'_>` is not implemented for `alloy_primitives::Uint<256, 4>`

I'm sort of a rust beginner; but it seems I can't really implement those traits. myself either due to the orphan rule.

**Comment by mattsse** [comment]
hmm, did you enable serde feature?

**Comment by miracle2k** [comment]
Oh no! I thought i checked for a feature, but somehow missed it. Thanks! 🙏
