### ISSUE TITLE
Issue encoding and decoding struct that contains an array  of dynamic bytes

### ISSUE THREAD

**Issue by Wizdave97** [alloy-rs/core#204]
### Component

sol-type, sol! macro

### What version of Alloy are you on?

0.2.0

### Operating System

macOS (Apple Silicon)

### Describe the bug

I have a this function in solidity code https://github.com/polytope-labs/substrate-ismp/blob/evm-contracts/pallet-ismp/evm/solidity/example.sol#L119  that abi encodes a struct `DispatchGet`

I'm encoding the struct with this code https://github.com/polytope-labs/substrate-ismp/blob/evm-contracts/pallet-ismp/evm/solidity/ismp_defs.sol#L117

The encoded bytes are then passed to a rust precompile by the evm runtime I'm using to execute the contract, 
I try to decode the encoded bytes here https://github.com/polytope-labs/substrate-ismp/blob/evm-contracts/pallet-ismp/evm/src/ismp_dispatcher_precompiles.rs#L92 using the equivalent type generated by the sol macro
but I get a ReserializationMismatch error, if I remove the array of dynamic bytes from the solidity struct, it decodes without any errors.

To run the tests and see the error

run `cargo +nightly test -p ismp-evm   get_dispatch -- --nocapture`

PS: If I try decoding the data with `validate` set to `false` it decodes but the field that contains the array of dynamic bytes, just contains an vectors of zeros.

**Comment by prestwich** [comment]
can you post the output of the solidity encoding?

For me, 
```
        bytes memory c = b.encodeGetDispatch(B.DispatchGet({
            dest: "0x1234567890123456789012345678901234567890",
            height: 1,
            keys: new bytes[](1),
            timeoutTimestamp: 1,
            gasLimit: 1
        }));
```

produces 

```
00000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002a30783132333435363738393031323334353637383930313233343536373839303132333435363738393000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000
```

and the following test passes:
```
#[test]
fn issue() {
    let encoded = hex_literal::hex!("00000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002a30783132333435363738393031323334353637383930313233343536373839303132333435363738393000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000");

    sol! {
        // An object for dispatching post requests to the IsmpDispatche
        struct DispatchGet {
            // bytes representation of the destination chain as utf8 string bytes
            bytes dest;
            // Height
            uint256 height;
            // the request body
            bytes[] keys;
            // Timeout
            uint256 timeoutTimestamp;
            // Gas limit that should be used to execute the response or timeout for this request
            uint256 gasLimit;
        }
    }

    DispatchGet::decode(&encoded, true).unwrap();
}
```

**Comment by Wizdave97** [comment]
This is the output of the solidity encoding for the data you posted onm my end is 
`00000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000141234567890123456789012345678901234567890000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000`

**Comment by Wizdave97** [comment]
when I try to decode the encoded  data you posted on my end, I get the same ReserializationMismatchError also

**Comment by Wizdave97** [comment]
What version of alloy are you using to for the test case?

**Comment by Wizdave97** [comment]
> What version of alloy are you using for the test case?

Just checked, there's only one version published

**Comment by Wizdave97** [comment]
This following test case also fails on my end, don't really understand why 

```rust
#[test]
fn issue() {
    use alloy_sol_types::SolType;
    use alloy_primitives::U256;

    sol! {
        // An object for dispatching post requests to the IsmpDispatche
        struct DispatchGet {
            // bytes representation of the destination chain as utf8 string bytes
            bytes dest;
            // Height
            uint256 height;
            // the request body
            bytes[] keys;
            // Timeout
            uint256 timeoutTimestamp;
            // Gas limit that should be used to execute the response or timeout for this request
            uint256 gasLimit;
        }
    }

    let get = DispatchGet {
        dest: hex::decode("1234567890123456789012345678901234567890").unwrap(),
        height: U256::try_from(200).unwrap(),
        keys: vec![vec![1u8; 64]],
        timeoutTimestamp: U256::try_from(200).unwrap(),
        gasLimit: U256::try_from(200).unwrap(),
    };

    let encoded = DispatchGet::encode(&get);

    let decoded = DispatchGet::decode(&encoded, true).unwrap();

    assert_eq!((decoded.gasLimit, decoded.dest, decoded.height, decoded.keys, decoded.timeoutTimestamp), (get.gasLimit, get.dest, get.height, get.keys, get.timeoutTimestamp));
}

**Comment by prestwich** [comment]
> What version of alloy are you using for the test case?

I'm using alloy at main. I suspect that this is a bug which has been fixed after release of 0.2.0. mind trying to use main instead of published?

**Comment by Wizdave97** [comment]
I'll give that a try

**Comment by Wizdave97** [comment]
The bug is fixed on the main branch, thanks for the assist
