### ISSUE TITLE
[Feature] Simple API to resolve `json-abi` item types

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/core#210]
### Component

dyn-abi, json-abi

### Describe the feature you would like

Example: in `ethabi` you can just call `Function::encode_input` to ABI-encode data with the function's selector and inputs. cc @prestwich

**Comment by davebryson** [comment]
I'm experimenting with this now to get a better understanding of alloy's APIs. What's the intended replacement for`ethabi Token`  in this context ... `SolType`?  Thanks!

**Comment by prestwich** [comment]
DynSolType is roughly equivalent to ParamKind

The way i would to this is extending the Resolve trait in dyn-abi to have a method that both resolves + encodes

**Comment by davebryson** [comment]
Here's one approach as a method on [Function](https://github.com/alloy-rs/core/blob/main/crates/json-abi/src/item.rs#L376)

```rust
pub fn encode_input(&self, args: DynAbiValue) -> Result<Vec<u8>> {
   let input_types = self
            .inputs
            .iter()
            .map(|i| i.resolve().expect("valid type"))
            .collect::<Vec<DynSolType>>();
   
    if !input_types.matches(&args) {
            Err(...)
    }
      
    let encoded_args = args.encode_params();
    // prepend selector... etc...
}
```
I'm actually working on a pull request for this.  However,  this approach requires `json_abi` to depend on `dyn_abi` which already depends on `json_abi`.... which depends on ... resulting in a cyclic deps problem.   Any thoughts on how to get around this?

**Comment by prestwich** [comment]
yeah, the circular dep is why we need to put this logic in the `Resolve` trait in `dyn-abi`. json-abi is strictly a dat format, and should not rely on the type system representation in `dyn-abi`

**Comment by davebryson** [comment]
@prestwich Ok, I think I understand what you're after now.

**Comment by davebryson** [comment]
@DaniPopes  Following on to this, is there interest in taking a similar approach to provide support for something like `event.parse_log()` to parse the log into DynSolValues?

**Comment by prestwich** [comment]
@DaniPopes should we come up with a struct that represents Events? 

```
struct DynEventType {
    topics: [Option<DynSolType>; 4],
    body: DynSolType
}

struct DynEvent {
    topics: [Option<DynSolValue>; 4],
    body: DynSolValue
}
```

**Comment by davebryson** [comment]
@DaniPopes @prestwich  I'm happy to work on this once you decide on the direction.  I've already roughed out an initial solution
