### ISSUE TITLE
[Feature] Support `yul` AST

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/core#237]
### Component

syn-solidity

### Describe the feature you would like

`yul` items are the only missing items from `syn-solidity`.

All nodes must implement:
- `std::fmt::Debug`
- `syn::parse::Parse`
- `crate::Spanned`

and should have a short 1 liner doc comment, optionally pointing to the [Solidity grammar reference](https://docs.soliditylang.org/en/latest/grammar.html) where possible.

### Additional context

See #199 for reference of how to complete the AST.

**Comment by mouseless-eth** [comment]
Currently working on this implementation
