### ISSUE TITLE
Prevent user from instantiating invalid `Param` instances by making at least 1 field private

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/core#240]
if public fields allow the user to create invalid instances, then we should at least consider making them non-public

_Originally posted by @prestwich in https://github.com/alloy-rs/core/pull/233#discussion_r1300362251_

**Comment by chirag-bgh** [comment]
@prestwich I can take this.

**Comment by prestwich** [comment]
ah my guide above is incorrect. because `name` and `type` need to be validated, they need to be private. no `_guard` needed

@DaniPopes has pointed out that this breaks mathcing and destructuring, so we should evaluate how worth it it is after seeing code. so there's a chance even if you do this work it won't get merged

**Comment by mahmudsudo** [comment]
can i take this ?
