### ISSUE TITLE
[Feature] `FixedBytes` should map to `FixedBytes`

### ISSUE THREAD

**Issue by rachel-bousfield** [alloy-rs/core#259]
### Component

primitives, sol-type

### Describe the feature you would like

Right now the [`SolType`](https://docs.rs/alloy-sol-types/0.3.2/alloy_sol_types/trait.SolType.html) impl for [`sol_data::FixedBytes`](https://docs.rs/alloy-sol-types/0.3.2/alloy_sol_types/sol_data/struct.FixedBytes.html) has the `RustType` `[u8; N]`.

We've worked around this in the [Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs) by introducing a new type, [`abi::FixedBytesSolType`](https://docs.rs/stylus-sdk/0.1.2/stylus_sdk/abi/struct.FixedBytesSolType.html), and foresee potential special casing around this quirk.

We propose that, as is already the case with integers, [`sol_data::FixedBytes`](https://docs.rs/alloy-sol-types/0.3.2/alloy_sol_types/sol_data/struct.FixedBytes.html) have the `RustType` [`alloy_primitives::FixedBytes`](https://docs.rs/alloy-primitives/0.3.3/alloy_primitives/struct.FixedBytes.html).

We're happy to help implement this change, which should be straightforward :)

**Comment by DaniPopes** [comment]
SGTM, I'll assign you to this issue then!

**Comment by prestwich** [comment]
I'm on board with this change

The main impact on users will be the change to the output type of decoding for sol types containing a `bytesN`, which seems fine. Can you make sure this change is propagated to the `DynSolValue::FixedBytes` as well, by having it wrap a `FixedBytes<32>` instead of a `[u8;32]`

**Comment by DaniPopes** [comment]
Hey @rachel-bousfield, do you still plan on working on this? Otherwise I can take over this issue

**Comment by rachel-bousfield** [comment]
Hey @DaniPopes feel free to take it -- we won't have time for the next couple of weeks but probably will after that. Happy either way and thanks!
