### ISSUE TITLE
[Feature] Implement human-readable ABI parser

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/core#291]
### Component

dyn-abi, json-abi, Other (please provide more details)

### Describe the feature you would like

- add `parse` methods to `alloy_json_abi::{Error, Event, Function}` that parses `$name($($inputs),*)($($outputs),*)` into these structs (outputs is just for `Function`)
- implement parser in `alloy-sol-type-parser`

**Comment by alessandromazza98** [comment]
Hi Dani, I'd like to try this one.

Just a question, do you want like three `impl` block for `Error, Event, Function`?

Also, when you say to implement the parser in `alloy-sol-type-parser` you mean to do the logic there and then in the `impl` block just call the real parser in `alloy-sol-type-parser`?

Thanks
