### ISSUE TITLE
EIP-712 compatible Serializable impl for dyn_abi::eip712::TypedData

### ISSUE THREAD

**Issue by edef1c** [alloy-rs/core#334]
### Component

dyn-abi

### Describe the feature you would like

TypedData seems to go to some effort to specifically name the `types` field `resolver` instead, taking pains to have a custom Deserializer impl that renames the field from `types` to `resolver` through an intermediate `TypedDataHelper` struct. There is no corresponding remapping for serialisation, and so the Serialize output is incompatible with both the Deserialize impl and EIP-712.

It's unclear to me why the field is named `resolver` to begin with, and it seems like it would save a bunch of hassle to just rename the field or at least mark it `#[serde(rename = "types")]`.

**Comment by prestwich** [comment]
> TypedData seems to go to some effort to specifically name the types field resolver instead, taking pains to have a custom Deserializer impl that renames the field from types to resolver through an intermediate TypedDataHelper struct

the intermediate deserializer exists because certain systems pass the json as a string in a larger json object, so the deserializer has to handle that

missing rename is fixed in #335

**Comment by edef1c** [comment]
> missing rename is fixed in https://github.com/alloy-rs/core/pull/335

Thanks! Glad to see roundtrip tests as well.
