### ISSUE TITLE
[Bug]  sol macro doesn't handle solidity idents that are rust keywords

### ISSUE THREAD

**Issue by Will-Smith11** [alloy-rs/core#343]
### Component

json-abi, sol! macro, syn-solidity

### Operating System

None

### Describe the bug

![image](https://github.com/alloy-rs/core/assets/44074786/4365e8bf-8b92-409f-96cf-96eddd735ee8)
![image](https://github.com/alloy-rs/core/assets/44074786/fb1f12cc-7b35-4bba-933d-7a21f50419ea)
https://etherscan.io/address/0xdef1c0ded9bec7f1a1670819833240f027b25eff#code

**Comment by DaniPopes** [comment]
Requires a bigger refactor, will be fixed with #82

**Comment by Will-Smith11** [comment]
@DaniPopes I have a branch that deals with this workaround (using r# when needed in SolIdent) if you want me to push it up
