### ISSUE TITLE
[Bug] Sol Macro doesn't handle duplicate Error names

### ISSUE THREAD

**Issue by Will-Smith11** [alloy-rs/core#344]
### Component

sol-types, syn-solidity

### Operating System

None

### Describe the bug

![image](https://github.com/alloy-rs/core/assets/44074786/fdfe39d0-6e67-4537-9821-16a100317ba1)
https://etherscan.io/address/0x1111111254eeb25477b68fb85ed929f73a960582#code
This error occurs on the 1Inch contract. Its caused due to the contract using different libraries for errors but same error name.
```solidity
library RouterErrors {
    error ReturnAmountIsNotEnough();
    error InvalidMsgValue();
    error ERC20TransferFailed();
}

library Errors {
    error InvalidMsgValue();
    error ETHTransferFailed();
}
```

**Comment by DaniPopes** [comment]
Solidity emits two identical error objects in the ABI, weird
