### ISSUE TITLE
[Bug] Expected Parenthesizes 

### ISSUE THREAD

**Issue by Will-Smith11** [alloy-rs/core#349]
### Component

sol! macro

### Operating System

None

### Describe the bug

![image](https://github.com/alloy-rs/core/assets/44074786/8746fe25-0155-4fb7-bc4a-6310de103e9f)
https://etherscan.io/address/0x080bf510fcbf18b91105470639e9561022937712#code

**Comment by Will-Smith11** [comment]
something similar but differnet wording of error message
![image](https://github.com/alloy-rs/core/assets/44074786/53f61580-8eff-4011-b74e-4315ac4f65a8)

**Comment by DaniPopes** [comment]
Looks like Solc 0.4.X ABI does not have `internalType`: we fallback to emitting `tuple` or `tuple[]` -> the parser expects a `tuple(...)` type -> no parens found

**Comment by DaniPopes** [comment]
I don't think we can do anything about this, since name information is lost, unless we make up names for each custom struct we encounter and emit it separately. At that point I'd rather just not support this since it blows up in complexity

**Comment by DaniPopes** [comment]
We could emit tuple types inline like `function f(address a, (uint, bool) b)`. This is not valid Solidity since there are no tuple types, but we do support it in `sol!`
