### ISSUE TITLE
[Bug] unresolved types

### ISSUE THREAD

**Issue by Will-Smith11** [alloy-rs/core#351]
### Component

sol! macro

### Operating System

None

### Describe the bug

https://etherscan.io/address/0x8638fbd429b19249bb3bcf3ec72d07a657e49642#code
![image](https://github.com/alloy-rs/core/assets/44074786/b660a696-d959-47d0-b245-7dd426e140c9)

**Comment by DaniPopes** [comment]
Same as https://github.com/alloy-rs/core/issues/347

**Comment by DaniPopes** [comment]
Worked around by emitting `address` when `"internalType": "contract ..."` in #354
