### ISSUE TITLE
[Feature] Implement ToSql and FromSql traits from postgres types for ethereum specific types

### ISSUE THREAD

**Issue by hhamud** [alloy-rs/core#365]
### Component

primitives, sol-types

### Describe the feature you would like

Implement ToSql and FromSql traits from postgres types for ethereum specific types, e.g H256, H160, U256, I256.

**Comment by prestwich** [comment]
this is already enabled for `U***` types via `ruint`'s `postgres` feature. We would likely accept a PR that adds feature-gated support for `I***` types and `FixedBytes<N>` types

**Comment by hhamud** [comment]
Is `ruint`already a part of this package or can we just integrate that portion of the package into this one?

**Comment by naps62** [comment]
Would a `diesel` feature-gated alternative be something you'd consider adding as well? afaik it has its own `FromSql`/`ToSql`, and `ruint` does not handle those

**Comment by prestwich** [comment]
if you make a PR to add diesel to ruint first and alloy-primitives second, we would consider it

@hhamud if you make a PR to add postgres and sqlx support to alloy-primitives, we'll likely merge quickly. I may do this if I have free time any time soonzz

**Comment by hhamud** [comment]
> if you make a PR to add diesel to ruint first and alloy-primitives second, we would consider it
> 
> @hhamud if you make a PR to add postgres and sqlx support to alloy-primitives, we'll likely merge quickly. I may do this if I have free time any time soon

Yeah I can get that done.
