### ISSUE TITLE
[Bug] json-abi erroring when a library function uses a struct defined in the library itself

### ISSUE THREAD

**Issue by Will-Smith11** [alloy-rs/core#370]
### Component

json-abi

### Operating System

None

### Describe the bug

![image](https://github.com/alloy-rs/core/assets/44074786/de4e4636-01f1-4aea-8dca-e78121ca5a09)

**Comment by Will-Smith11** [comment]
comes from this line
![image](https://github.com/alloy-rs/core/assets/44074786/bf56f921-c7ad-4945-8b9c-2dd5b4204d10)

**Comment by DaniPopes** [comment]
Sorry can you expand on this? What is `contract.abi` and `contract.addresses`?

**Comment by Will-Smith11** [comment]
contract.abi is just the abi of the contract pulled from etherscan and the address likewise is the address from etherscan. 

> Sorry can you expand on this? What is `contract.abi` and `contract.addresses`?

**Comment by DaniPopes** [comment]
Optimistically closing as fixed, I don't have much information as to what the actual issue is here.
