### ISSUE TITLE
[Bug] infinite recusion on 0xC10DdeaCd46146a9Ca6E27467443383Ee080EfbC

### ISSUE THREAD

**Issue by Will-Smith11** [alloy-rs/core#371]
### Component

sol! macro

### Operating System

None

### Describe the bug

![image](https://github.com/alloy-rs/core/assets/44074786/1eda4e08-81d6-4646-9192-3c796a309e71)
pretty sure this is an error given its deployed on etherscan and builds without any errors

**Comment by DaniPopes** [comment]
Can you please post a link to the contract?
