### ISSUE TITLE
Move `define_udt!` decl macro to `sol!` proc macro

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/core#39]
https://github.com/alloy-rs/core/blob/0c21fcc48eab0b52c20d3e98c739bac862aad8ff/crates/sol-types/src/types/udt.rs#L7

**Comment by mahmudsudo** [comment]
can i take this ?

**Comment by mahmudsudo** [comment]
can some extra details of the usage be given ?

**Comment by DaniPopes** [comment]
> can i take this ?

Sure, go ahead!

It's mostly just porting the `macro_rules!` to proc macro code using `quote!` in here:

https://github.com/alloy-rs/core/blob/0c21fcc48eab0b52c20d3e98c739bac862aad8ff/crates/sol-macro/src/expand/udt.rs#L9

You can look at the other files in the expand module for examples

**Comment by mahmudsudo** [comment]
would start on it immediately

**Comment by fgimenez** [comment]
@mahmudsudo are you working on this? if not I'd like to give it a try
