### ISSUE TITLE
[Bug] sol! procedural macro getting error from rust-analyzer

### ISSUE THREAD

**Issue by cuckflong** [alloy-rs/core#427]
### Component

sol! macro

### What version of Alloy are you on?

alloy-primitives v0.4.2 alloy-sol-types v0.4.2 alloy-primitives v0.4.2 (*)  alloy-sol-macro v0.4.2 (proc-macro)

### Operating System

Other (please specify)

### Describe the bug

Example
![image](https://github.com/alloy-rs/core/assets/28383100/ddf7b031-392e-41dc-9c73-13d21c4479bf)

**Comment by DaniPopes** [comment]
The code compiles fine, it's a bug in RA. See https://github.com/rust-lang/rust-analyzer/issues/15909 - it should be fixed in the latest "pre-release" version on VSCode. If not, you can disable it with `"rust-analyzer.diagnostics.disabled": ["E0046"]`.
