### ISSUE TITLE
[Bug] `abi_decode` panic when using sol types of fixed bytes

### ISSUE THREAD

**Issue by jimzk** [alloy-rs/core#433]
### Component

sol-types

### Operating System

macOS (Apple Silicon)

### Describe the bug

Reproduction

```rs
use alloy_primitives::fixed_bytes;
use alloy_sol_types::{sol, SolType};
sol! {
    #[derive(Debug, Default)]
    struct FullReport {
        bytes32[3] report_context;
        bytes      report_blob;
        bytes32[]  raw_rs;
        bytes32[]  raw_ss;
        bytes32    raw_vs;
    }
}
let full_report = FullReport {
    report_context: [
        fixed_bytes!("0006015a2de20abc8c880eb052a09c069e4edf697529d12eeae88b7b6867fc81"),
        fixed_bytes!("00000000000000000000000000000000000000000000000000000000080f7906"),
        fixed_bytes!("0000000000000000000000000000000000000000000000000000000000000000"),
    ],
    report_blob: hex::decode("0002191c50b7bdaf2cb8672453141946eea123f8baeaa8d2afa4194b6955e68300000000000000000000000000000000000000000000000000000000655ac7af00000000000000000000000000000000000000000000000000000000655ac7af000000000000000000000000000000000000000000000000000000000000138800000000000000000000000000000000000000000000000000000000000a1f6800000000000000000000000000000000000000000000000000000000655c192f000000000000000000000000000000000000000000000000d130d9ecefeaae30").unwrap().into(),
    raw_rs: vec!(
        fixed_bytes!("d1e3d8b8c581a7ed9cfc41316f1bb8598d98237fc8278a01a9c6a323c4b5c331"),
        fixed_bytes!("38ef50778560ec2bb08b23960e3d74f1ffe83b9240a39555c6eb817e3f68302c"),
    ),
    raw_ss: vec!(
        fixed_bytes!("7fb9c59cc499a4672f1481a526d01aa8c01380dcfa0ea855041254d3bcf45536"),
        fixed_bytes!("2ce612a86846a7cbb640ddcd3abdecf56618c7b24cf96242643d5c355dee5f0e"),
    ),
    raw_vs: fixed_bytes!("0001000000000000000000000000000000000000000000000000000000000000"),
};
// let full_report: FullReport = Default::default();
// let encoded = full_report.abi_encode();
let encoded = FullReport::abi_encode(&full_report);
println!("encoded: {:?}", hex::encode(&encoded));
let full_report = FullReport::abi_decode(&encoded, true).unwrap();
println!("full_report: {:?}", full_report);

```

Panic message
```
called `Result::unwrap()` on an `Err` value: TypeCheckFail { expected_type: "Solidity pointer (uint32)", data: "0006015a2de20abc8c880eb052a09c069e4edf697529d12eeae88b7b6867fc81" }
```

When I remove `bytes32[3] report_context;` then it works.

**Comment by jimzk** [comment]
Hi @DaniPopes I wonder why the encoding bytes is different from other tools?

I encode a variable of same type with same data by [`ethabi`](https://github.com/rust-ethereum/ethabi), the abi-encode result is `0006015a2de20abc8c880eb052a09c069e4edf697529d12eeae88b7b6867fc8100000000000000000000000000000000000000000000000000000000080f7906000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000240000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e00002191c50b7bdaf2cb8672453141946eea123f8baeaa8d2afa4194b6955e68300000000000000000000000000000000000000000000000000000000655ac7af00000000000000000000000000000000000000000000000000000000655ac7af000000000000000000000000000000000000000000000000000000000000138800000000000000000000000000000000000000000000000000000000000a1f6800000000000000000000000000000000000000000000000000000000655c192f000000000000000000000000000000000000000000000000d130d9ecefeaae300000000000000000000000000000000000000000000000000000000000000002d1e3d8b8c581a7ed9cfc41316f1bb8598d98237fc8278a01a9c6a323c4b5c33138ef50778560ec2bb08b23960e3d74f1ffe83b9240a39555c6eb817e3f68302c00000000000000000000000000000000000000000000000000000000000000027fb9c59cc499a4672f1481a526d01aa8c01380dcfa0ea855041254d3bcf455362ce612a86846a7cbb640ddcd3abdecf56618c7b24cf96242643d5c355dee5f0e`

However in [the above snippet](https://github.com/alloy-rs/core/issues/433#issue-2007893079), result of `abi_encode` is `00000000000000000000000000000000000000000000000000000000000000200006015a2de20abc8c880eb052a09c069e4edf697529d12eeae88b7b6867fc8100000000000000000000000000000000000000000000000000000000080f7906000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000240000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e00002191c50b7bdaf2cb8672453141946eea123f8baeaa8d2afa4194b6955e68300000000000000000000000000000000000000000000000000000000655ac7af00000000000000000000000000000000000000000000000000000000655ac7af000000000000000000000000000000000000000000000000000000000000138800000000000000000000000000000000000000000000000000000000000a1f6800000000000000000000000000000000000000000000000000000000655c192f000000000000000000000000000000000000000000000000d130d9ecefeaae300000000000000000000000000000000000000000000000000000000000000002d1e3d8b8c581a7ed9cfc41316f1bb8598d98237fc8278a01a9c6a323c4b5c33138ef50778560ec2bb08b23960e3d74f1ffe83b9240a39555c6eb817e3f68302c00000000000000000000000000000000000000000000000000000000000000027fb9c59cc499a4672f1481a526d01aa8c01380dcfa0ea855041254d3bcf455362ce612a86846a7cbb640ddcd3abdecf56618c7b24cf96242643d5c355dee5f0e`, which has extra leading bytes `0000000000000000000000000000000000000000000000000000000000000020`.

**Comment by DaniPopes** [comment]
The equivalent to `ethabi` would be `abi_encode_params`.

**Comment by wtdcode** [comment]
Found this thread due to lack of documenting the difference between `abi_encode` and `abo_encode_params` and try to leave my own understanding here.

Given a type T,

- `abi_encode` unconditionally encodes it as `(T)`, regardless `T` is tuple or not.
- `abi_encode_params` encodes it as `T` if `T` is already a tuple, but encodes `(T)` if `T` is not a tuple.

This could be easily verified by:

```
use alloy::primitives::Bytes;
use alloy::{dyn_abi::SolType, primitives::U256, sol_types::SolValue};
use alloy::dyn_abi::abi::TokenSeq;
alloy::sol! {
    struct S {
        bytes s; // make S contain dynamic types
        uint a;
        uint b;
    }
}
fn main() {
    let s = S {
        s: Bytes::new(),
        a: alloy::uint!(1_U256),
        b: alloy::uint!(2_U256)
    };

    let t: bool = <S as SolType>::Token::IS_TUPLE;

    println!("is_tuple: {}", t);
    println!("{}", alloy::hex::encode(s.abi_encode()));
    println!("{}", alloy::hex::encode(s.abi_encode_params()));
}
```

and this gives:

```
is_tuple: true
00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000
```

Note `abi_encode` prefixes the data with `0000000000000000000000000000000000000000000000000000000000000020`, which actually is the offset to the nested tuple `T` (`S` in the example above).

With `abi_encode_params`, we don't have nested tuple, so `0000000000000000000000000000000000000000000000000000000000000060` is the offset to the `bytes`.

So I'm guessing the reason given the prevailing usages of `sol!` and the answer seems to `abi.encode`. For example, 

```
struct S {
    bytes s;
    uint a;
    uint b;
}
contract CounterTest is Test {


    function test_bytes() public {
        uint a;
        uint b;
        bytes memory s;
        S memory ss;

        (s, a, b) = abi.decode(hex"0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000", (bytes, uint, uint));
        (ss) = abi.decode(hex"00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000", (S));
    }
}
```

Note the difference of the two `abi.decode` here.
