### ISSUE TITLE
[Feature]  Serve online document on git pages

### ISSUE THREAD

**Issue by clearloop** [alloy-rs/core#440]
### Component

Other (please provide more details)

### Describe the feature you would like

Since the crates are not fully published yet, developers hardly can get an overview of this toolset by now which is also blocking issuing bugs, contribution, etc.

**Comment by DaniPopes** [comment]
All crates are published on crates.io, and as such are also available on docs.rs. Example: [alloy-primitives](https://crates.io/crates/alloy-primitives) ([docs.rs](https://docs.rs/alloy-primitives/))
