### ISSUE TITLE
generate bindings for constructors

### ISSUE THREAD

**Issue by rouzwelt** [alloy-rs/core#482]
### Component

sol-types, sol! macro

### Describe the feature you would like

right now when using `sol!` macro for some json artifact or inline solidity contract, all the types for functions/events/errors are generated and can be easily instantiated and Abi-encoded/decoded, as they would appear in `contractNameCalls`, `contractNameEvents` and `contractNameErrors`, however there is no similar thing for constructor of the underlying contract.

So Im suggesting that a similar functionality be provided for constructors, possibly with an option of building the deploy data with the contract `bytecode` if it was available.

**Comment by DaniPopes** [comment]
https://github.com/alloy-rs/core/pull/493
