### ISSUE TITLE
[Bug] `Log` doesn't allow implementation of traits for non-default generic parameter

### ISSUE THREAD

**Issue by Wodann** [alloy-rs/core#544]
### Component

primitives

### What version of Alloy are you on?

0.6.3

### Operating System

Linux

### Describe the bug

The `Log` generic uses a default type `= LogData`. This means that for any traits that are implemented for `Log`, the traits are only implemented for `Log::<LogData>`. Given that Rust does not allow implementation of external traits on external types, this prohibits people from implementing traits on the `Log` type when using a locally defined `CustomLogData`.

E.g. when trying to `impl alloy_rlp::Encodable for LogData<CustomLogData>` this would fail with the compiler error:

```bash
only traits defined in the current crate can be implemented for types defined outside of the crate define and implement a trait or new type instead
```

To solve this, the trait implementations in https://github.com/alloy-rs/core/blob/main/crates/primitives/src/log.rs#L120 should be generic; e.g. `impl<LogDataT: SomeTrait> alloy_rlp::Encodable for Log<LogDataT> { .. }`.

**Comment by prestwich** [comment]
without capturing log encoding semantics in primitives, how would you design `SomeTrait`?

**Comment by Wodann** [comment]
My proposal would be:

```rs
trait ExecutionLogData {
  fn topics(&self) -> &[B256];

  fn data(&self) -> &Bytes;
}
```

This should provide you with all of the information to implement the current implementations of `alloy_rlp::Encodable` and `alloy_rlp::Decodable`.

**Comment by prestwich** [comment]
The goal of parameterizing over the data is to allow replacing it with deserialized versions and dropping the serialized version.

So this might work for something like `trait IntoLogData { fn into(&self) -> LogData }`

**Comment by Wodann** [comment]
Yeah, a simple `LogDataT: Into<LogData>` would suffice too for the two rlp traits 🙂

**Comment by prestwich** [comment]
it needs a bit more complexity, as it would require RLP coding which is fallible. so it migh be something more like:

```
impl<T: TryInto<LogData, Error = alloy_rlp::Error>> alloy_rlp::Encodable for Log<T> { ... }
impl<T: TryInto<LogData, Error = Infallible>> alloy_rlp::Encodable for Log<T> { ... }
```
