### ISSUE TITLE
[Bug] Use stable clippy instead of nightly

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/core#566]
### Component

Other (please provide more details)

### Operating System

None

### Describe the bug

Nightly clippy includes unstable and changing lints and results in random CI breakage

**Comment by DaniPopes** [comment]
Sorry I disagree, if CI doesn't break now it will break when a stable release happens, it's not really that much different.

**Comment by prestwich** [comment]
happening once at known intervals is way, way better than happening randomly
