### ISSUE TITLE
[Bug] Documentation is broken

### ISSUE THREAD

**Issue by MathieuDutSik** [alloy-rs/core#591]
### Component

Other (please provide more details)

### What version of Alloy are you on?

0.7.0

### Operating System

macOS (Intel)

### Describe the bug

The problem occurs on the page `https://docs.rs/alloy-core/0.7.0/alloy_core/`.
If we click on `alloy-primitives` we get the following error:
```
unexpected character 'p' while parsing major version number
```

**Comment by DaniPopes** [comment]
We'd have to choose between links working on GitHub or on docs.rs because we're using the same file for both (through symlinks). I'm fine with how it is right now, it's unfortunate but on docs.rs you can see the modules at the bottom of the page.
