### ISSUE TITLE
[Feature][Primitive] Allow ParseUnits to be converted to u128

### ISSUE THREAD

**Issue by NicolasWent** [alloy-rs/core#598]
### Component

primitives

### Describe the feature you would like

The gas configurations have been set to u128 instead of U256 in the alloy [TransactionBuilder](https://github.com/alloy-rs/alloy/blob/24396144b51b15df8b6d72e502feb10af3b68b5d/crates/network/src/transaction/builder.rs#L151)

It would be nice to have an `into()` implementation for a [ParseUnits](https://github.com/alloy-rs/core/blob/7e68fa76118d7c138820789efab377174316ca38/crates/primitives/src/utils/units.rs#L135) to convert it directly to u128.

This way we would be able to set the max priority fee per gas (and max_fee_per_gas) more smoothly:
```rust
// Currently not working:
my_transaction_builder.max_priority_fee_per_gas(parse_units("0.1", "gwei").unwrap().into());
```

Instead of the current workaround:
```rust
let max_priority_fee_per_gas: U256 = parse_units("0.1", "gwei").unwrap().into();
my_transaction_build.max_priority_fee_per_gas(max_priority_fee_per_gas.to());
```

**Comment by DaniPopes** [comment]
This should be `TryFrom` since 256 -> 128 bits is fallible.
