### ISSUE TITLE
[Bug] Documentation isn't generating correctly for Signature

### ISSUE THREAD

**Issue by kayabaNerve** [alloy-rs/core#605]
### Component

primitives

### Operating System

Other (please specify)

### Describe the bug

Searching the documentation for "recover" does not show "Signature::recover", and there are other similarly missing items for Signature.

**Comment by prestwich** [comment]
I think this is related to [this](https://github.com/rust-lang/rust/pull/119997) was included in rust 1.77. 

cc @DaniPopes I am not sure why the docs.rs build would be on 1.80-nightly and still not be adding the appropriate impls here

**Comment by prestwich** [comment]
I have confirmed that local generation produces the impl blocks as expected
