### ISSUE TITLE
[Bug] Uint's don't zero-pad when formatted with formatting specifier

### ISSUE THREAD

**Issue by stanleyjzheng** [alloy-rs/core#622]
### Component

primitives

### What version of Alloy are you on?

0.7.2

### Operating System

macOS (Apple Silicon)

### Describe the bug

Ethers properly formats zero-padding with the `format!()` macro, but it seems like alloy's uints ignore it. A minimal example would be

```rust
let x = U256::from(10);

assert_eq!(
    format!("{:0>width$}", x, width = 18_usize),
    format!("{:0>width$}", x.to_string(), width = 18_usize)
)
```

**Comment by DaniPopes** [comment]
Can you please re-open the issue in [recmo/uint](https://github.com/recmo/uint)

**Comment by stanleyjzheng** [comment]
Ah got it, thanks
