### ISSUE TITLE
[Bug] requiring "json" feature for "sol!" macro is a breaking change

### ISSUE THREAD

**Issue by tlovell-sxt** [alloy-rs/core#628]
### Component

sol! macro

### What version of Alloy are you on?

0.7.3

### Operating System

Linux

### Describe the bug

When rebuilding a project that depends on the sol macro, or using `cargo update`, the code unexpectedly failed to compile. This is because between version `0.7.2` and `0.7.3`, the macro now requires the `json` feature to be enabled (#626). This is not too big of an issue as we can just enable the `json` feature as well, but it should count as a breaking change so dependents don't break unexpectedly.

**Comment by DaniPopes** [comment]
Sorry about that, releasing a patch.
