### ISSUE TITLE
[Bug] Panic in `Parity::inverted`

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/core#630]
### Component

primitives

### Operating System

None

### Describe the bug

This line needs to handle the 0 case
https://github.com/alloy-rs/core/blob/main/crates/primitives/src/signature/parity.rs#L109

**Comment by jafar75** [comment]
I can send a PR for this issue
just to be ensured, for 0 case, it must return 0?

**Comment by prestwich** [comment]
for `inverted(0)` should return `1`. even tho this means the `inverted` operation is no longer symmetrical. we don't expect real users to ever hit this edge case
