### ISSUE TITLE
[Bug] Function created with sol! macro does not perform correct abi_encode() for function selector

### ISSUE THREAD

**Issue by mesozoic-technology** [alloy-rs/core#631]
### Component

sol-types, sol! macro

### Operating System

macOS (Apple Silicon)

### Describe the bug

I reproduced the issue below. This is for version 0.7.4.

The abi encoded hex bytes produced by `replicateCall{...}.abi_encode()` does not result in the correct encoding of the function's selector, which was derived from a forge script and printed out afterwards. 

https://github.com/mesozoic-technology/rust-sketches/blob/main/src/main.rs

**Comment by DaniPopes** [comment]
The signature in the Rust code you provided is `replicate(bytes,bytes,bytes,address)`, which is correct for the given `sol!` function. What signature are you expecting?

**Comment by prestwich** [comment]
independently verifying the 4-byte with cast gives the same result as `sol!`
<img width="471" alt="Screenshot 2024-05-22 at 09 38 15" src="https://github.com/alloy-rs/core/assets/10149425/e992300e-b1ab-427e-a990-6aad0583aa67">

which we can see matches the `sol!` output of the `rust-sketch` bin
<img width="225" alt="Screenshot 2024-05-22 at 09 38 44" src="https://github.com/alloy-rs/core/assets/10149425/e5f221cc-aff4-40e9-a961-46b42e5fe34b">

Can you say what function definition gave `0x6fc310f8` and how it was printed from the forge script?

**Comment by mesozoic-technology** [comment]
Sorry, you're right, I'm wrong. Had a huge cold yesterday and put the similarly named but incorrect contract into forge to derive that "expected selector". 

I was trying to encode a call to Multicall3 and it was working when I did not include any calls, but when including this call, failed. Combined with my head pounding, jumped to a false conclusion
