### ISSUE TITLE
[Bug] `sol!` only accepts string literal

### ISSUE THREAD

**Issue by wtdcode** [alloy-rs/core#651]
### Component

sol! macro

### What version of Alloy are you on?

0.7.4

### Operating System

Linux

### Describe the bug

`sol!` seems only to support string literals, i.e., `LitStr.` For instance:

```
sol!(T, "[]"); // Works
sol!(T, concat!("[","]")); // Doesn't work
const s: &str = "[]";
sol!(T, s); // Doesn't work either
```

Is it possible to support a constant `&str` instead? This would be helpful to support something like `concat!(std::env!("OUT_DIR"), ...)`

**Comment by wtdcode** [comment]
Seems not possible as https://github.com/rust-lang/rust/issues/69133

**Comment by DaniPopes** [comment]
We parse out environment variables with $ENV but that's about as much as you can do unfortunately

**Comment by chris13524** [comment]
Bumping this, is there a way to reference environment variables in the latest version of `sol!`? This doesn't seem to work:
```
sol!(
    #[allow(missing_docs)]
    #[sol(rpc)]
    SafeProxyFactory,
    "$OUT_DIR/../../../../.foundry/forge/out/SafeProxyFactory.sol/SafeProxyFactory.json"
);
```
