### ISSUE TITLE
[Bug] Regression: code examples are missing in rendered docs

### ISSUE THREAD

**Issue by sergiimk** [alloy-rs/core#656]
### Component

contract

### Operating System

None

### Describe the bug

Current rendered documentation has some code examples missing, see:
https://alloy-rs.github.io/alloy/alloy/sol_types/macro.sol.html

**Comment by DaniPopes** [comment]
For now you can view them [on docs.rs](https://docs.rs/alloy-sol-macro/latest/alloy_sol_macro/macro.sol.html)
