### ISSUE TITLE
Why redefine this mask function when ruint crate already have same mask function?

### ISSUE THREAD

**Issue by rongyi** [alloy-rs/core#695]
https://github.com/alloy-rs/core/blob/adcf7adfa1f35c56e6331bab85b8c56d32a465f1/crates/primitives/src/signed/int.rs#L107

https://github.com/recmo/uint/blob/c4616bdb1bcdaa991ef23f9808c56c86127625ea/src/lib.rs#L321

**Comment by mattsse** [comment]
this is indeed duplicated and could be reused since it appears to be public ruint api
