### ISSUE TITLE
[Feature] Implement debug for function calls

### ISSUE THREAD

**Issue by NicolasWent** [alloy-rs/core#721]
### Component

sol! macro

### Describe the feature you would like

Hello,

When I decode some function input, I would like to be able to print debug it to see the parameters. It can be useful to debug our code.

### Additional context

Example usage:

```rust
if let Ok(decoded) = myCall::abi_decode(&data.input, true) {
    // here is crashed because it doesn't implement Debug
    println!("Decoded: {decoded:?}");
}

**Comment by DaniPopes** [comment]
You can annotate functions and other items with normal rust attributes that will be applied in the generated code.
