### ISSUE TITLE
[Bug] failed to parse ABI-generated tokens into a Solidity AST: expected `,`.

### ISSUE THREAD

**Issue by chris13524** [alloy-rs/core#746]
### Component

Other (please provide more details)

### What version of Alloy are you on?

forge 0.2.0 (0079a11 2024-09-10T00:20:21.629283000Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

I get this error:

```
Generating bindings for 201 contracts
Error: 
failed to parse ABI-generated tokens into a Solidity AST: expected `,`.
This is a bug. We would appreciate a bug report: https://github.com/alloy-rs/core/issues/new/choose
```

When running `forge bind` in the root folder of this repo: https://github.com/erc7579/smartsessions/tree/main

**Comment by DaniPopes** [comment]
https://github.com/alloy-rs/core/pull/747 fixes this bug, but the ABI will generate invalid Rust code because of https://github.com/alloy-rs/core/issues/744
