### ISSUE TITLE
Improve `dyn-abi` encoding performance

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/core#75]
Benchmark from #57, as of commit 64bf519b81c9c204a63b9154d15f92b23b0a3cae:

```clojure
ethabi/encode/single    time:   [82.202 ns 82.358 ns 82.525 ns]                                 
ethabi/encode/struct    time:   [164.10 ns 165.43 ns 166.85 ns]                                 

ethabi/decode/word      time:   [34.678 ns 34.765 ns 34.861 ns]                                
ethabi/decode/dynamic   time:   [78.638 ns 78.759 ns 78.910 ns]                                  

dyn-abi/encode/single   time:   [68.373 ns 68.550 ns 68.741 ns]                                  
dyn-abi/encode/struct   time:   [683.96 ns 684.70 ns 685.52 ns]                                   

dyn-abi/decode/word     time:   [54.141 ns 54.203 ns 54.266 ns]                                
dyn-abi/decode/dynamic  time:   [80.822 ns 80.932 ns 81.053 ns]                                   

sol-types/encode/single time:   [42.843 ns 43.007 ns 43.207 ns]                                     
sol-types/encode/struct time:   [49.110 ns 49.171 ns 49.235 ns]                                    

sol-types/decode/word   time:   [1.3375 ns 1.3389 ns 1.3405 ns]                                   
sol-types/decode/dynamic                                                                             
                        time:   [39.279 ns 39.478 ns 39.721 ns]
```

---

Maybe we can skip tokenizing by encoding directly the `DynSolValue`? Looking at the `"struct"` bench, ethabi is much more concise because of `ethabi::encode(tokens: &[ethabi::Token])`, while dyn-abi has to declare all the types, and then also clone the input on each call.

_Originally posted by @DaniPopes in https://github.com/alloy-rs/core/issues/57#issuecomment-1572135980_

**Comment by prestwich** [comment]
> Maybe we can skip tokenizing by encoding directly the DynSolValue? Looking at the "struct" bench, ethabi is much more concise because of ethabi::encode(tokens: &[ethabi::Token]), while dyn-abi has to declare all the types, and then also clone the input on each call.

this is the official plan now

**Comment by moh-eulith** [comment]
I implemented this here: https://github.com/moh-eulith/alloy-core/tree/dynperf
but I don't consider it PR worthy for the following reason:
I don't see a good test suite (did I miss it?). The variation in input is near infinite. 
a) Is there another task to add tests?
b) Are there tests elsewhere that can be copied over?

**Comment by moh-eulith** [comment]
Sorry, I just noticed the recent work on this. You might want to play with that branch above. The struct case is noticeably faster.

**Comment by prestwich** [comment]
the tests that need to be ported are in `sol-type` 
[encoder](https://github.com/alloy-rs/core/blob/main/crates/sol-types/src/coder/encoder.rs#L173)
[decoder](https://github.com/alloy-rs/core/blob/main/crates/sol-types/src/coder/decoder.rs#L240-L607)

**Comment by prestwich** [comment]
closing this as we've made significant improvements and added tests
