### ISSUE TITLE
[Bug] `map::HashMap::new()` not implemented

### ISSUE THREAD

**Issue by Wollac** [alloy-rs/core#751]
### Component

primitives

### What version of Alloy are you on?

alloy-primitives v0.8.5

### Operating System

None

### Describe the bug

With the recently added `alloy_primitives::map` and the default features (i.e. `std`, `map`, `map-fxhash`), using `HashMap::new()` results in a rather cryptic error. This is due to the fact that `new()` forwards to `std::collections::HashMap::new()` which uses the `RandomState` hasher, instead of the new default `FxHasher`. The same happens for `with_capacity()`. 
Everything works as expected for `HashMap::default()` or in `no-std` where the `hashbrown` crate is used instead.

Since these are arguably the recommended ways to use std `HashMap`, it would be nice if this worked as expected, or at least made that fact clear in the documentation.

**Comment by DaniPopes** [comment]
Not this library's problem, this is already mentioned in the std docs
