### ISSUE TITLE
impl a better way to get the function from word

### ISSUE THREAD

**Issue by malik672** [alloy-rs/core#752]
### Component

other

### Describe the feature you would like

for the function.rs in primitive crate, in the from_word function, we can simply create a function from a word using ` unsafe { Self(*(word.0.as_ptr() as *const [u8; 24])) }` than `   Self(FixedBytes(word[..24].try_into().unwrap()))`

**Comment by malik672** [comment]
> They're equivalent, but the current implementation doesn't use unsafe. I fail to see how it's better
> 
> https://godbolt.org/z/bx4v46nsj

nope they are not, it can't be the same performance for all input sizes
let me pull up something real fast

**Comment by malik672** [comment]
@DaniPopes

**Comment by DaniPopes** [comment]
Look at the `TryFrom<&[T]> for &[T; N]`, there is no other way to implement this and they compile to the same LLVM and assembly instructions; please don't continue this issue

**Comment by malik672** [comment]
> Look at the `TryFrom<&[T]> for &[T; N]`, there is no other way to implement this and they compile to the same LLVM and assembly instructions; please don't continue this issue

I'm not going to continue the issue; I'm just arguing that just because they compile to the same assembly instructions doesn't mean they will run at the same time for all input sizes

identical assembly does not guarantee identical performance
@DaniPopes

**Comment by malik672** [comment]
> They're equivalent, but the current implementation doesn't use unsafe. I fail to see how it's better
> 
> https://godbolt.org/z/bx4v46nsj

the better I was talking about here is just runtime speed
