### ISSUE TITLE
Default hasher `foldhash` queries the time

### ISSUE THREAD

**Issue by Wollac** [alloy-rs/core#767]
### Component

primitives

### What version of Alloy are you on?

alloy-primitives v0.8.6

### Operating System

None

### Describe the bug

The recent update to `foldhash` as the default hasher for map in `v0.8.6` introduces a dependency on `std::time` within `foldhash`. This poses a problem for targets like `zkvm`, where time is not available, leading to errors.

This change effectively breaks compatibility with `zkvm` and potentially other targets lacking `std::time`.  Projects relying on Alloy and targeting these platforms will no longer work successfully.

**Comment by DaniPopes** [comment]
I've removed the default in https://github.com/alloy-rs/core/pull/771, but this is also the default hasher for Hashbrown, so consider opening an issue/PR in foldhash to extend disabling the time query cfg
