### ISSUE TITLE
[Bug] compilation broken on version 0.5.2 when `contract` feature is enabled

### ISSUE THREAD

**Issue by klefevre** [alloy-rs/core#778]
### Component

json-abi

### What version of Alloy are you on?

0.5.2

### Operating System

macOS (Apple Silicon)

### Describe the bug

The 0.8.9 version of the `alloy-json-abi` crate is broken (I didn't check previous version). 

To reproduce:

```shell
cargo new test-alloy
cd test-alloy
cargo add alloy --features contract
cargo build
```

**Comment by markjung96** [comment]
I also encountered same issue.

**Comment by mertwole** [comment]
Same issue for me. Also this issue persists for versions `0.2.0`, `0.3.0` and `0.4.0`. I believe it's caused by https://github.com/serde-rs/serde/issues/2844 . I've tried pinning minor version of `serde` by doing `serde = "=1.0.210"` in `Cargo.toml` and it resolved problem for me.

**Comment by DaniPopes** [comment]
This is a bug in serde: https://github.com/serde-rs/serde/issues/2844
Moved to there
