### ISSUE TITLE
[Bug] Cannot compile alloy-json-abi at 0.7.6

### ISSUE THREAD

**Issue by Ifechukwudaniel** [alloy-rs/core#783]
### Component

json-abi

### What version of Alloy are you on?

0.7.6

### Operating System

Linux

### Describe the bug

 I updated it to 0.7.6  and cannot compile it due to errors inside alloy-json-abi.

Here's the output when building:
![ksnip_20241024-133033](https://github.com/user-attachments/assets/581cd52f-06a8-4c96-8294-5709c014cceb)

![ksnip_20241024-133033](https://github.com/user-attachments/assets/664d8fb9-2414-4926-a2a2-2541878e9cbe)

**Comment by Ifechukwudaniel** [comment]
@grandima

**Comment by DaniPopes** [comment]
Please update all your crates at once and to the latest version
