### ISSUE TITLE
Rename `Sol*::Tuple` to `Parameters`/`Arguments`

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/core#91]
Rename `SolError::Tuple` to `SolError::Parameters`, `SolCall::Tuple` to `SolCall::Arguments`

**Comment by shawnharmsen** [comment]
would like to take a stab at this please, will open pr soon

**Comment by prestwich** [comment]
only gotcha is that it needs to be changed in the proc macro codegen in `sol-macro/src/expand/` as well as in the traits in `sol-type/src/types`
